# Generated by ard-make version 1.2

BOARD_TAG = uno
ARDMK_DIR = /usr/local/opt/arduino-mk
# AVR_TOOLS_DIR = /Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/
# MONITOR_PORT = /dev/cu.usbmodem14131

include $(ARDMK_DIR)/Arduino.mk

# include kit-generated headers
CPPFLAGS += -I ../include